# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Build settings
theme: minimal-mistakes-jekyll

# Theme for minimal-mistakes-jekyll
minimal_mistakes_skin: "sunrise" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise" "default"
locale: "en"
title: "JG's Playground Blog"
subtitle: "...be a good one. -Abe"
name: &its_me "Jose O. Gonzalez"
description: "A site to share code, ideas, etc."
#teaser: "assets/images/venize_night.jpg"
url: "http://jgplayground.com"
baseurl: ""

# Search posts
search: true
search_provide: algolia
algolia:
  application_id: SFJRAYIBYV
  index_name: prod_Main
  search_only_api_key: 7b09f7940d8d5df3c611777e951ba041
  powered_by: true # true (default), false


og_image: "/assets/images/bio-photo.jpg"
social:
  type: Person # Person or Organization (defaults to Person)
  #name: # If the user or organization name differs from the site's name
  links:
    - "https://twitter.com/jose42086"
    - "https://github.com/jose423"
    - "https://www.linkedin.com/in/jose-gonzalez-a01aa64a/"

# Site Author
author:
  name     : *its_me
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "I am a computer engineer that loves learning about the IT world."
  location : "Texas, USA"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: &twit "https://twitter.com/jose42086"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: &git "https://github.com/jose423"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: &linked "https://www.linkedin.com/in/jose-gonzalez-a01aa64a/"

# Site footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: &twit "https://twitter.com/jose42086"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: &linked "https://www.linkedin.com/in/jose-gonzalez-a01aa64a/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  # _foo collections
  # - scope:
  #     path: ""
  #     type: foo
  #   valuses:
  #     layout: single

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Chicago

# Taxonomy
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Reading Files
include:
  - _pages

# Compression of html files
compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment

# End of minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  # Used by minimal-mistakes-jekyll
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-gist
  # End of minimal-mistakes-jekyll

# defaults:
#   - 
#     scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "posts"
#       title: "My Title"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
